-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgusWUmsc0LxWHeGVx
erRMzWdTG6ozzfCWaHw/Q1RxcBCgCgYIKoZIzj0DAQehRANCAASgpTVWzxR+vKnn
/yPKkSX8N6am1IPVxCPjziFiVS45vn1blpYlu7UANAYjTS7qEZW/Qsz1j4+regpw
6lwjE8Y/
-----END PRIVATE KEY-----